#!/bin/bash
if [ $# -ne 1 ]; then
	echo 'wrong number of parameter'
	exit 1
fi
if [ $1 = "up" ]; then
	service --status-all | grep '\[ + \]' | awk -F' ' '{print $4}'
elif [ $1 = "down" ]
then
	service --status-all | grep '\[ - \]' | awk -F' ' '{print $4}'
else
	echo 'Wrong value'
fi
